#!/bin/bash

## Compress and upload bag files for BWI log data.

DEFAULT_DIR=~/.ros/bwi/bwi_logging
LOGGER=/usr/bin/logger          # syslog command

# Function to print command argument usage:
usage() {
    echo "Usage: $(basename $0) [options] PREFIX"
    echo ""
    echo "Compress and upload files matching '\$PREFIX_*.bag' to the main BWI"
    echo "server.  These bags are normally stored in '~/.ros/bwi/bwi_logging'."
    echo "Successfully uploaded compressed bags are either deleted or optionally"
    echo "saved in a subdirectory named 'kept'."
    echo ""
    echo "Options:"
    echo -e "\t-c\tcompress only, do not upload"
    echo -e "\t-d\tdirectory containing bags"
    echo -e "\t  \t (default: $DEFAULT_DIR)"
    echo -e "\t-h\tprint this message"
    echo -e "\t-k\tkeep the compressed files after uploading"
    echo -e "\t-n\tdry run, only prints bag info for the selected files"
    echo -e "\t-u\tupload only, do not compress"
    echo -e "\t-w\tnumber of seconds to wait before starting"
}

# Default options
compress=true
dir=$DEFAULT_DIR
dry_run=""
keep=false
upload=true
waitsecs=0

# Get optional parameters
while getopts 'cd:hknuw:' opt; do
    case $opt in
        c)  upload=false     ;;
        d)  dir="$OPTARG"    ;;
        h)  usage; exit 0    ;;
        k)  keep=true        ;;
        n)  dry_run="-n"     ;;
        u)  compress=false   ;;
        w)  waitsecs=$OPTARG ;;
        *)  usage; exit 9    ;;
    esac
done

# handle PREFIX positional parameter
shift $((OPTIND-1))
if [ $# != 1 ]
then    echo "Exactly one PREFIX parameter is required:"
        usage; exit 9
fi
prefix=$1

## debug output for parameter testing:
#echo "  compress: $compress"
#echo "  dir:      $dir"
#echo "  dry_run:  $dry_run"
#echo "  keep:     $keep"
#echo "  prefix:   $prefix"
#echo "  upload:   $upload"
#echo "  waitsecs:   $waitsecs"

if [ $waitsecs -gt 0 ]
then    echo "waiting $waitsecs seconds before starting."
fi

suffix="_*.bag"
glob=$prefix$suffix

echo "Processing bag files in $dir."
cd $dir

# Make a subdirectory for the compressed files.
COMPRESSED="compressed"
mkdir -p $COMPRESSED

if $compress
then
        # See if there are bags to compress
        if /bin/ls $glob 1> /dev/null 2>&1
        then
                # make sure rosbag command is accessible via some ROS environment
                if ! /usr/bin/which rosbag >/dev/null
                then    source /opt/ros/indigo/setup.bash
                fi

                if [ "$dry_run" = "-n" ]
                then    rosbag info $glob
                        # no upload done with -n
                        exit 0
                fi

                # Compress the bags
                $LOGGER 'compressing BWI logs...'
                if rosbag compress --output-dir=$COMPRESSED $glob
                then    /bin/rm -f $glob
                fi
                $LOGGER 'completed BWI logs compression'
                if [ $? != 0 ]
                then    exit $?
                fi
        else    echo "No new files matching $glob found."
        fi
fi

if $upload
then    # upload any compressed bags
        cd $COMPRESSED
        $LOGGER 'starting BWI logs upload...'
        if bwilab upload $dry_run $prefix
        then    if $keep
                then    mkdir -p ../kept
                        /bin/mv $glob ../kept
                else    /bin/rm $glob
                fi
        fi
        $LOGGER 'completed BWI logs upload'
fi

exit $?
