#!/bin/bash

## Run a script in the /usr/local/lib/bwi_local directory.

if [ $# -lt 1 ]
then    echo "usage: `basename $0` command [args]"
        exit 9
fi

CMD_DIR="/usr/local/lib/bwi_local"
cmd=$1

# issue sensible error message if command invalid
if [ ! -x "$CMD_DIR/$cmd" ]
then    echo "$(basename $0): \"$cmd\" command not found."
        exit 2
fi

# run the command with any remaining arguments
shift
exec $CMD_DIR/$cmd $*
