#!/bin/bash

## Upload saved bag files from the current directory.

if [ "$#" -gt "2" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
then    echo "usage: $(basename $0) [option]"
        echo ""
        echo "Uploads files matching 'bwi_*.bag' from the current directory to the"
        echo "main BWI server. \$HOSTNAME should be the lowest-level domain name."
        echo "By default, will delete the files after uploading"
        echo ""
        echo "Supports these options:"
        echo -e "\t-h [--help]\tprint this help message"
        echo -e "\t-p\tspecify the bag prefix (will upload nodes matching 'PREFIX_*.bag'"
        echo -e "\t-e\tkeep the files after uploading"
        exit 1
fi

# Default operations
del_opt="--remove-sent-files"
prefix="bwi"

# Get parameters
while getopts 'k:p:' opt; do
    case $opt in
        p)  prefix="$OPTARG" ;;
        k)  del_opt=""       ;;
        *)  exit 1           ;;
    esac
done

suffix="_*.bag"
glob=$prefix$suffix

# Ensure the hostname is set
if [ "$HOSTNAME" == "" ]
then    echo "$HOSTNAME must be set for this operation"
        exit 9
fi

# Make a subdirectory for the compressed files.
COMPRESSED="compressed"
mkdir -p $COMPRESSED

# Commands
RSYNC=/usr/bin/rsync
SERVER=nixons-head.csres.utexas.edu
TARGET_DIR=~bwilab/robot/$HOSTNAME

# See if there are bags to upload
if ! ls $glob 1> /dev/null 2>&1
then    echo "No new bag files (matching $glob) here to upload."
  exit 0
fi

# Make sure the target directory exists:
ssh -p40 $SERVER mkdir -p $TARGET_DIR

# Compress the data
rosbag compress --output-dir=$COMPRESSED $glob
rm -f bwi_*.bag

# Upload the data
cd $COMPRESSED || exit -1
echo $RSYNC -avz $del_opt -e 'ssh -p40' $glob $SERVER:$TARGET_DIR
exec $RSYNC -avz $del_opt -e 'ssh -p40' $glob $SERVER:$TARGET_DIR
