#!/bin/sh

## Upload saved bag files from the current directory.
#
#  MUST run using /bin/sh, because bash defeats the setuid authorization.

# Function to print command argument usage:
usage() {
    echo "usage: $(basename $0) [options] PREFIX"
    echo ""
    echo "Uploads files from the current directory to the main BWI"
    echo "server. \$HOSTNAME should be set to the robot's name."
    echo ""
    echo "Supports these options:"
    echo "  -h  print this help message"
    echo "  -n  dry run, do no transfers"
}

# Default operations
dry_run=""

# Get parameters
while getopts 'nh' opt; do
    case $opt in
        n)  dry_run="-n"     ;;
        h)  usage; exit 0    ;;
        *)  usage; exit 9    ;;
    esac
done

# handle PREFIX positional parameter
shift $((OPTIND-1))
if [ $# != 1 ]
then    echo "Exactly one PREFIX parameter is required:"
        usage; exit 9
fi
prefix=$1

## debug output for parameter testing:
#echo "    dry_run:  $dry_run"
#echo "    prefix:   $prefix"

suffix="_*.bag"
glob=$prefix$suffix

# Ensure the hostname is set
if [ "$HOSTNAME" = "" ]
then    HOSTNAME=$(hostname)
fi

# Constants
RSYNC=/usr/bin/rsync
SERVER=nixons-head.csres.utexas.edu
TARGET_DIR=~bwilab/robot/$HOSTNAME

# See if there are bags to upload
if ! /bin/ls $glob 1> /dev/null 2>&1
then    echo "No files matching $glob to upload."
        exit 1
fi

# Make sure the target directory exists:
/usr/bin/ssh $SERVER mkdir -p $TARGET_DIR

# Upload the data
exec $RSYNC -avz $dry_run -e 'ssh' $glob $SERVER:$TARGET_DIR
